### ISSUE TITLE
Wiki: 500 con troppe nested quote

### ISSUE THREAD

**Issue by Alby1** [royal-games/royalnet#70]
quando si fa la citazione
(questa sotto:)

> ciao

si possono mettere più ">"
ma solo con un massimo di 196, dopo di ché esplode e da questo errore:
![Immagine](https://user-images.githubusercontent.com/30355916/59872895-0edba380-939b-11e9-82a5-0224f229a5fa.png)

(questi sono 196): ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")

questo è quello che succede btw:
![Immagine](https://user-images.githubusercontent.com/30355916/59872710-a987b280-939a-11e9-87c5-cc4a3c4a47e8.png)

**Comment by Steffo99** [comment]
Grazie @Alby1 !
