### ISSUE TITLE
Wiki: Strikethrough non disponibile

### ISSUE THREAD

**Issue by Alby1** [royal-games/royalnet#71]
Non funziona striketrough
edit:
![Immagine](https://user-images.githubusercontent.com/30355916/59873515-780fe680-939c-11e9-858e-421c77548663.png)
final result:
![Immagine](https://user-images.githubusercontent.com/30355916/59873563-9249c480-939c-11e9-8bb9-7f1548a1783d.png)

**Comment by Steffo99** [comment]
Huh. Non è supportato nel renderer che uso in Python. Ero convinto di sí...

**Comment by Steffo99** [comment]
Integrata in #79.
